# Generated by Django 2.1 on 2019-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('page', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'booktable',
            },
        ),
    ]
