# Generated by Django 2.1 on 2019-12-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191202_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='book_name',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
